[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True
check_untyped_defs = True

# External packages without stubs
[mypy-geoip2.*]
ignore_missing_imports = True

[mypy-watchdog.*]
ignore_missing_imports = True

[mypy-flask_compress.*]
ignore_missing_imports = True
